---
title: "GMT Online Games -- Data Cleaning"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: 
  github_document:
    toc: true
---

```{r packages}
library(lubridate)
library(readxl)
library(writexl)
library(magrittr)
library(tidyverse)
```

```{r}
df_to_keep = c(
  "df_to_keep",
  "df_fruit1", "dict_fruit1",
  "df_fruit2", "dict_fruit2",
  "df_fruit3", "dict_fruit3",
  "df_fruit4", "dict_fruit4",
  "df_card1", "dict_card1",
  "df_card2", "dict_card2",
  "df_card3", "dict_card3",
  "df_card4", "dict_card4"
)
```


<!-- ======================================================================= -->


# Fruit Clapping Tasks

```{r}
source("fruit1.R")
source("fruit2.R")
source("fruit3.R")
source("fruit4.R")
```


<!-- ======================================================================= -->


# Card Sorting Tasks

```{r}
# source("card1.R")
source("card2.R")
source("card3.R")
source("card4.R")
```



<!-- ======================================================================= -->


# Export data

```{r export_data}
list(fruit1 = df_fruit1,
     fruit2 = df_fruit2,
     fruit3 = df_fruit3,
     fruit4 = df_fruit4,
     card2 = df_card2,
     card3 = df_card3,
     card4 = df_card4) %>% 
  write_xlsx("../data/gmt_clean.xlsx")
```

```{r export_dict}
list(fruit1 = dict_fruit1,
     fruit2 = dict_fruit2,
     fruit3 = dict_fruit3,
     fruit4 = dict_fruit4,
     card2 = dict_card2,
     card3 = dict_card3,
     card4 = dict_card4) %>% 
  write_xlsx("../data/gmt_dictionary.xlsx")
```


<!-- ======================================================================= -->


# Session info

```{r session_info, include = TRUE}
sessionInfo()
```