---
title: "GMT Online Games — Data Descriptives"
author: "Carina Fan"  
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r chunk_options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r packages}
library(psych)
library(readxl)
library(magrittr)
library(tidyverse)
```

```{r data}
path = "../data/gmt_clean.xlsx"

all_data = excel_sheets(path) %>% 
  lapply(read_excel, path = path)

names(all_data) = excel_sheets(path)
```

```{r functions}
nice_histogram = function(dataframe, var, binwidth) {
  dataframe %>% 
    ggplot(aes_string(x = var)) +
    geom_histogram(binwidth = binwidth,
                   fill = "hotpink3",
                   colour = "hotpink3",
                   alpha = .4) +
    xlim(-.1, 1.1) +
    ylab("Count") +
    theme_bw()
}
```


<!-- ======================================================================= -->


# Fruit Tasks
 
## Fruit Task 1

```{r}
df.fruit1 = all_data$fruit1

df.fruit1$non_pears_correct_proportion = df.fruit1$non_pears_correct / df.fruit1$non_pears_shown
df.fruit1$pears_correct_proportion = df.fruit1$pears_correct / df.fruit1$pears_shown
```

```{r}
describe(df.fruit1)
```

```{r fig.show = "hold", out.width = "50%"}
df.fruit1 %>% 
  nice_histogram("pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of pears correct")

df.fruit1 %>% 
  nice_histogram("non_pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of non-pears correct")
```

## Fruit Task 2

```{r}
df.fruit2 = all_data$fruit2

df.fruit2$non_pears_correct_proportion = df.fruit2$non_pears_correct / df.fruit2$non_pears_shown
df.fruit2$pears_correct_proportion = df.fruit2$pears_correct / df.fruit2$pears_shown
```

```{r}
describe(df.fruit2)
```

```{r fig.show = "hold", out.width = "50%"}
df.fruit2 %>% 
  nice_histogram("pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of pears correct")

df.fruit2 %>% 
  nice_histogram("non_pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of non-pears correct")
```

## Fruit Task 3 

```{r}
df.fruit3 = all_data$fruit3

df.fruit3$non_pears_correct_proportion = df.fruit3$non_pears_correct / df.fruit3$non_pears_shown
df.fruit3$pears_correct_proportion = df.fruit3$pears_correct / df.fruit3$pears_shown
df.fruit3$stop_spaces_proportion = df.fruit3$stop_spaces / df.fruit3$stops
```

```{r}
describe(df.fruit3)
```

```{r fig.show = "hold", out.width = "50%"}
df.fruit3 %>% 
  nice_histogram("pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of pears correct")

df.fruit3 %>% 
  nice_histogram("non_pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of non-pears correct")

df.fruit3 %>% 
  nice_histogram("stop_spaces_proportion", binwidth = .1) +
  xlab("Proportion of (incorrect) space bar responses to 'Stop'")
```

## Fruit Task 4 

```{r}
df.fruit4 = all_data$fruit4

df.fruit4$non_pears_correct_proportion = df.fruit4$non_pears_correct / df.fruit4$non_pears_shown
df.fruit4$pears_correct_proportion = df.fruit4$pears_correct / df.fruit4$pears_shown
df.fruit4$stop_spaces_proportion = df.fruit4$stop_spaces / df.fruit4$stops
df.fruit4$stop_ups_proportion = df.fruit4$stop_ups / df.fruit4$stops
df.fruit4$slow_stops_proportion = df.fruit4$slow_stops / df.fruit4$stops
```

```{r}
describe(df.fruit4)
```

```{r fig.show = "hold", out.width = "50%"}
df.fruit4 %>% 
  nice_histogram("pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of pears correct")

df.fruit4 %>% 
  nice_histogram("non_pears_correct_proportion", binwidth = .1) +
  xlab("Proportion of non-pears correct")

df.fruit4 %>% 
  nice_histogram("stop_spaces_proportion", binwidth = .1) +
  xlab("Proportion of (incorrect) space bar responses to 'Stop'")

df.fruit4 %>% 
  nice_histogram("stop_ups_proportion", binwidth = .1) +
  xlab("Proportion of correct up arrow responses to 'Stop'")

df.fruit4 %>% 
  nice_histogram("slow_stops_proportion", binwidth = .1) +
  xlab("Proportion of slow responses to 'Stop'")

df.fruit4 %>% 
  nice_histogram("incorrect_ups", binwidth = 1) +
  xlab("Number of incorrect up arrow responses\n(i.e., hit when 'Stop' wasn't presented)") +
  xlim(-1, 8)
```


<!-- ======================================================================= -->


# Card Sorting Tasks

## Card Sort 1

```{r}
df.card1 = all_data$card1

df.card1$fives_correct_proportion = df.card1$fives_correct / df.card1$fives_shown
df.card1$cards_correct_proportion = df.card1$cards_correct / df.card1$cards_shown
```

```{r}
describe(df.card1)
```

```{r fig.show = "hold", out.width = "50%"}
df.card1 %>% 
  nice_histogram("fives_correct_proportion", binwidth = .1) +
  xlab("Proportion of fives sorted correctly")

df.card1 %>% 
  nice_histogram("cards_correct_proportion", binwidth = .1) +
  xlab("Proportion of cards sorted correctly")
```

## Card Sort 2

```{r}
df.card2 = all_data$card2

df.card2$fives_correct_proportion = df.card2$fives_correct / df.card2$fives_shown
df.card2$cards_correct_proportion = df.card2$cards_correct / df.card2$cards_shown
```

```{r}
describe(df.card2)
```

```{r fig.show = "hold", out.width = "50%"}
df.card2 %>% 
  nice_histogram("fives_correct_proportion", binwidth = .1) +
  xlab("Proportion of fives sorted correctly")

df.card2 %>% 
  nice_histogram("cards_correct_proportion", binwidth = .1) +
  xlab("Proportion of cards sorted correctly")
```

## Card Sort 3

```{r}
df.card3 = all_data$card3

df.card3$fives_correct_proportion = df.card3$fives_correct / df.card3$fives_shown
df.card3$cards_correct_proportion = df.card3$cards_correct / df.card3$cards_shown
```

```{r}
describe(df.card3)
```

```{r fig.show = "hold", out.width = "50%"}
df.card3 %>% 
  nice_histogram("fives_correct_proportion", binwidth = .1) +
  xlab("Proportion of fives sorted correctly")

df.card3 %>% 
  nice_histogram("cards_correct_proportion", binwidth = .1) +
  xlab("Proportion of cards sorted correctly")
```

## Card Sort 4

```{r}
df.card4 = all_data$card4

df.card4$fives_correct_proportion = df.card4$fives_correct / df.card4$fives_shown
df.card4$cards_correct_proportion = df.card4$cards_correct / df.card4$cards_shown
df.card4$repetitions_correct_proportion = df.card4$repetitions_correct / df.card4$repetitions_heard
```

```{r}
describe(df.card4)
```

```{r fig.show = "hold", out.width = "50%"}
df.card4 %>% 
  nice_histogram("fives_correct_proportion", binwidth = .1) +
  xlab("Proportion of fives sorted correctly")

df.card4 %>% 
  nice_histogram("cards_correct_proportion", binwidth = .1) +
  xlab("Proportion of cards sorted correctly")

df.card4 %>% 
  nice_histogram("repetitions_correct_proportion", binwidth = .1) +
  xlab("Proportion of repetitions correctly responded to")

df.card4 %>% 
  nice_histogram("ups_incorrect", binwidth = 1) +
  xlab("Number of incorrect up arrow responses\n(i.e., hit when repetition wasn't presented)") +
  xlim(-1, 8)
```


<!-- ======================================================================= -->


# Complex Tasks

# Complex Tasks 1

```{r}
df.complex1 = all_data$complex1
```


<!-- ======================================================================= -->


# Session info

```{r session_info, include = TRUE}
sessionInfo()
```